from PyQt5 import QtCore, QtGui, QtWidgets
from student import *
from firebase import *
import re


class Ui_DataEntryWindow(object):
    def setupUi(self, DataEntryWindow):
        DataEntryWindow.setObjectName("DataEntryWindow")
        DataEntryWindow.setEnabled(True)
        DataEntryWindow.resize(513, 333)


        self.centralwidget = QtWidgets.QWidget(DataEntryWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 491, 271))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.studentInfotitle = QtWidgets.QLabel(self.formLayoutWidget)


        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(14)
        self.studentInfotitle.setFont(font)
        self.studentInfotitle.setAlignment(QtCore.Qt.AlignCenter)
        self.studentInfotitle.setObjectName("studentInfotitle")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.studentInfotitle)
        self.studentIdLabel = QtWidgets.QLabel(self.formLayoutWidget)


        font = QtGui.QFont()
        font.setPointSize(11)
        self.studentIdLabel.setFont(font)
        self.studentIdLabel.setObjectName("studentIdLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.studentIdLabel)
        self.studentIdInput = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.studentIdInput.setFont(font)
        self.studentIdInput.setObjectName("studentIdInput")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.studentIdInput)
        self.studentNameLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.studentNameLabel.setFont(font)
        self.studentNameLabel.setObjectName("studentNameLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.studentNameLabel)
        self.studentNameInput = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.studentNameInput.setFont(font)
        self.studentNameInput.setObjectName("studentNameInput")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.studentNameInput)
        self.studentSectionLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.studentSectionLabel.setFont(font)
        self.studentSectionLabel.setObjectName("studentSectionLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.studentSectionLabel)
        self.studentSectionInput = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.studentSectionInput.setFont(font)
        self.studentSectionInput.setObjectName("studentSectionInput")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.studentSectionInput)
        self.studentDobLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.studentDobLabel.setFont(font)
        self.studentDobLabel.setObjectName("studentDobLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.studentDobLabel)
        self.dobInput = QtWidgets.QDateEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.dobInput.setFont(font)
        self.dobInput.setObjectName("dobInput")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.dobInput)
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Meiryo UI")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.label)
        self.engLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.engLabel.setFont(font)
        self.engLabel.setObjectName("engLabel")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.engLabel)
        self.engMarks = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.engMarks.setObjectName("engMarks")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.engMarks)
        self.mathLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mathLabel.setFont(font)
        self.mathLabel.setObjectName("mathLabel")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.mathLabel)
        self.mathMarks = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.mathMarks.setObjectName("mathMarks")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.mathMarks)
        self.evsLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.evsLabel.setFont(font)
        self.evsLabel.setObjectName("evsLabel")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.evsLabel)
        self.evsMarks = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.evsMarks.setObjectName("evsMarks")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.evsMarks)
        self.saveBtn = QtWidgets.QPushButton(self.centralwidget)
        self.saveBtn.setGeometry(QtCore.QRect(10, 290, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.saveBtn.setFont(font)
        self.saveBtn.setObjectName("saveBtn")
        self.clearBtn = QtWidgets.QPushButton(self.centralwidget)
        self.clearBtn.setGeometry(QtCore.QRect(190, 290, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.clearBtn.setFont(font)
        self.clearBtn.setObjectName("clearBtn")
        self.clearBtn.clicked.connect(self.clearData)


        self.exitBtn = QtWidgets.QPushButton(self.centralwidget)
        self.exitBtn.setGeometry(QtCore.QRect(390, 290, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.exitBtn.setFont(font)
        self.exitBtn.setObjectName("exitBtn")
        DataEntryWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(DataEntryWindow)
        QtCore.QMetaObject.connectSlotsByName(DataEntryWindow)

        self.saveBtn.clicked.connect(self.saveData)

    def retranslateUi(self, DataEntryWindow):
        _translate = QtCore.QCoreApplication.translate
        DataEntryWindow.setWindowTitle(_translate("DataEntryWindow", "Data Entry Prep"))
        self.studentInfotitle.setText(_translate("DataEntryWindow", "Student Info"))
        self.studentIdLabel.setText(_translate("DataEntryWindow", "Student ID"))
        self.studentNameLabel.setText(_translate("DataEntryWindow", "Student Name"))
        self.studentSectionLabel.setText(_translate("DataEntryWindow", "Section"))
        self.studentDobLabel.setText(_translate("DataEntryWindow", "Date of Birth"))
        self.label.setText(_translate("DataEntryWindow", "Marks Entry"))
        self.engLabel.setText(_translate("DataEntryWindow", "English Marks"))
        self.mathLabel.setText(_translate("DataEntryWindow", "Math Marks"))
        self.evsLabel.setText(_translate("DataEntryWindow", "EVS Marks"))
        self.saveBtn.setText(_translate("DataEntryWindow", "SAVE"))
        self.clearBtn.setText(_translate("DataEntryWindow", "CLEAR"))
        self.exitBtn.setText(_translate("DataEntryWindow", "EXIT"))

    def saveData(self):
        id = self.studentIdInput.text()
        pattern = re.compile("[0-9][0-9]-[0-9][0-9][0-9][0-9]")
        id_bool = bool(pattern.match(id))        

        eng = self.engMarks.text()
        math = self.mathMarks.text()
        evs = self.evsMarks.text()
        marks_bool = eng.isnumeric() and math.isnumeric() and evs.isnumeric()

        name = self.studentNameInput.text()
        section = self.studentSectionInput.text()
        dob = self.dobInput.text()

        msg = QtWidgets.QMessageBox()

        if id_bool and marks_bool:
            stud = ClassPrepStudent(id, name, dob, section)        
            stud.putMarks(int(eng), int(math), int(evs))
            data = stud.createData()
            putintoDatabase(data)
            stud.printDetails()

            msg.setIcon(QtWidgets.QMessageBox.Information)
            msg.setWindowTitle("Success!!")
            msg.setText("Data saved successfully!")
            msg.exec_()
            self.clearData()
        else:
            msg.setIcon(QtWidgets.QMessageBox.Critical)
            msg.setWindowTitle("Error!!")
            msg.setText("Invalid data")
            msg.exec_()            

    def clearData(self):
        self.studentIdInput.clear()
        self.studentNameInput.clear()
        self.studentSectionInput.clear()
        self.dobInput.clear()
        self.engMarks.clear()
        self.mathMarks.clear()
        self.evsMarks.clear()
